### ISSUE TITLE
在改时区为GMT-4之后，新发布的文章，都自动改为1969年...

### ISSUE THREAD

**Issue by Ericjsz** [typecho/typecho#1077]
### 1. 该问题的重现步骤是什么？
后台：设置>基本>时区 (把默认时区改为 **GMT-4**)>**保存设置**
后台: 撰写文章>发布时间>点击**现在**(设置成当前时间) >最后**完成**
查看发布后, 发现文章被自动改为**1969年**

### 2. 你期待的结果是什么？实际看到的又是什么？
希望可以改时区后可以不影响文章正常的发布时间
我在**正式版上面复现, 发现改时区后, 不影响文章的发布时间**, 而开发版会
我个人主要用于延时发布, 目前只能使用默认时间, 这样的话发延时不会出错

### 3. 问题出现的环境

- 操作系统版本：CentOS 8.3.2011(Py3.7.9)
- Apache/NGINX 版本：nginx/1.18.0
- 数据库版本：MySQL 5.6.50-log
- PHP 版本：5.6.40
- Typecho 版本：1.2 (18.1.29)
- 浏览器版本：Chrome 89.0.4389.82

[//]: # (如有图片请附上截图)
![时区设定](https://cdn.jsdelivr.net/gh/ericjsz/img/2021/02/image-20210321022127001.png)
![发布新文章后台显示](https://cdn.jsdelivr.net/gh/ericjsz/img/2021/02/image-20210321022103001.png)

**Comment by Atombuck** [comment]
有1.2版么？最新不是1.1么？ 895538081 ***@***.*** 签名由 网易邮箱大师 定制 在2021年03月21日 14:26，Ericjsz 写道： 1. 该问题的重现步骤是什么？ 后台：设置>基本>时区 (把默认时区改为 GMT-4)>保存设置 后台: 撰写文章>发布时间>点击现在(设置成当前时间) >最后完成 查看发布实现自动改为1969年 2. 你期待的结果是什么？实际看到的又是什么？ 希望可以改时区后可以不影响文章正常的发布时间. 我个人主要用于延时发布, 目前只能使用默认时间, 这样的话发延时不会出错 3. 问题出现的环境 操作系统版本：CentOS 8.3.2011(Py3.7.9) Apache/NGINX 版本：nginx/1.18.0 数据库版本：MySQL 5.6.50-log PHP 版本：5.6.40 Typecho 版本：1.2 (18.1.29) 浏览器版本：Chrome 89.0.4389.82 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Ericjsz** [comment]
> 有1.2版么？最新不是1.1么？ 895538081 ***@***.*** 签名由 网易邮箱大师 定制 在2021年03月21日 14:26，Ericjsz 写道： 1. 该问题的重现步骤是什么？ 后台：设置>基本>时区 (把默认时区改为 GMT-4)>保存设置 后台: 撰写文章>发布时间>点击现在(设置成当前时间) >最后完成 查看发布实现自动改为1969年 2. 你期待的结果是什么？实际看到的又是什么？ 希望可以改时区后可以不影响文章正常的发布时间. 我个人主要用于延时发布, 目前只能使用默认时间, 这样的话发延时不会出错 3. 问题出现的环境 操作系统版本：CentOS 8.3.2011(Py3.7.9) Apache/NGINX 版本：nginx/1.18.0 数据库版本：MySQL 5.6.50-log PHP 版本：5.6.40 Typecho 版本：1.2 (18.1.29) 浏览器版本：Chrome 89.0.4389.82 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我指的是最新的开发版，在博客后台最底下它显示的是版本号为1.2 (18.1.29)。
![](https://cdn.jsdelivr.net/gh/ericjsz/img/2021/02/image-20210321112819001.png)
