### ISSUE TITLE
如何安装访问日志 记录浏览者来源等IP信息等

### ISSUE THREAD

**Issue by xianqiangzhao** [typecho/typecho#1102]
### 3. 问题出现的环境

- 操作系统版本：
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：
- Typecho 版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by shiertx** [comment]
推荐使用 TE插件仓库 的 Access 插件~



发自我的小米手机在 zhaoxianqiang ***@***.***>，2021年6月2日 下午9:28写道：

1. 该问题的重现步骤是什么？

2. 你期待的结果是什么？实际看到的又是什么？

3. 问题出现的环境



操作系统版本：

Apache/NGINX 版本：

数据库版本：

PHP 版本：

Typecho 版本：

浏览器版本：





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/typecho/typecho/issues/1102",

"url": "https://github.com/typecho/typecho/issues/1102",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by xianqiangzhao** [comment]
> TE插件仓库 的 Access
谢谢，我找找看
